// JavaScript Document
/*
一进入就向History_Query类发送含有flag = 1的Ajax请求
将返回的图片路径和名字和不同的id和访问时间设置给视频历史记录相应的地方

点击视频就向History_Query类发送含有flag = 1的Ajax请求
将返回的图片路径和名字和不同的id和访问时间设置给视频历史记录相应的地方

点击画作就向History_Query类发送含有flag = 2的Ajax请求
将返回的图片路径和名字和不同的id和访问时间设置给视频历史记录相应的地方

点击游戏设定集就向History_Query类发送含有flag = 3的Ajax请求
将返回的图片路径和名字和不同的id和访问时间设置给视频历史记录相应的地方

点击游戏原声集就向History_Query类发送含有flag = 4的Ajax请求
将返回的图片路径和名字和不同的id和访问时间设置给视频历史记录相应的地方

点击游戏周边就向History_Query类发送含有flag = 5的Ajax请求
将返回的图片路径和名字和不同的id和访问时间设置给视频历史记录相应的地方

点击历史记录后面的删除按钮时（建议不同id设给删除按钮）
向History_Delete类发送含有该历史记录不同id的Ajax请求
如果返回1则刷新页面
 */
